### ISSUE TITLE
Is the 9/27 Point Loma sample an anomaly?

### ISSUE THREAD

**Issue by jasonbmiller** [andersen-lab/SARS-CoV-2_WasteWater_San-Diego#128]
As always, thank you all for keeping us informed. It is invaluable for those of us who are still trying to avoid COVID.

I'm seeing that the last data point (9/27) for Point Loma is suddenly high. Is that a legitimate spike or an anomaly? It's quite a cliffhanger.

Thank you so much!

<img width="1097" alt="Screenshot 2023-10-04 at 8 09 03 AM" src="https://github.com/andersen-lab/SARS-CoV-2_WasteWater_San-Diego/assets/13813610/fd09973f-b0e6-4dbd-b2bd-749f8cba441e">

**Comment by joshuailevy** [comment]
Hi @jasonbmiller! 
While the sample has passed all of our standard QC, any particular measurement is subject to noise in both the sampling and laboratory steps. That said, it's not particularly unexpected to see a jump given the elevated viral loads we've been seeing and the recent emergence of variants like EG.5. We should hopefully have some new data over the next few days to further investigate this.

**Comment by jasonbmiller** [comment]
Hi @joshuailevy 

Thank you for getting back to me. I understand and I agree. I just wish it didn't look so dire.

You all are the best and we really appreciate what do!

--Jason

**Comment by joshuailevy** [comment]
Of course! Seems like the follow up sample viral loads (just added as part of PR #129 ) are a fair bit lower... they're still elevated, but that jump does not appear to be reflected in these samples. 

Josh
