### ISSUE TITLE
Another July spike is gone as soon as it starts

### ISSUE THREAD

**Issue by jasonbmiller** [andersen-lab/SARS-CoV-2_WasteWater_San-Diego#195]
As always, thank you all for keeping us informed. It is invaluable for those of us who are still trying to avoid COVID.

Is the last spike a legitimate spike or an anomaly? We noticed that it ended as soon as it started. The baseline remains pretty high as it has been all year.

Thank you so much!

**Comment by sandyarmstrong** [comment]
Also curious about this. I recently learned about wastewaterscan.org, which seems to do its own collection/normalization, and [their data for Point Loma](https://data.wastewaterscan.org/tracker/?charts=CiQQACABSABSBjNhM2ZhMVoGTiBHZW5leEKKAQZlYzA5MGPAAQE%3D&selectedChartId=ec090c) looks different (more worrisome):

![image](https://github.com/andersen-lab/SARS-CoV-2_WasteWater_San-Diego/assets/155076/f5cf9ec6-e747-4766-855e-961e9755c7c3)

Compared to SEARCH:

![image](https://github.com/andersen-lab/SARS-CoV-2_WasteWater_San-Diego/assets/155076/21a62dbf-b455-422d-b3d5-f47d7f43638b)

**Comment by joshuailevy** [comment]
Hey Jason and Sandy - thanks for reaching out! 

Regarding @jasonbmiller's question: I think it's likely a real trend, as we often see exponential growth/decay during these waves of transmission. There doesn't seem to be any reason to suspect that there's any issue with those samples, as far as I'm aware.  Four replicates were tested for each one, and quality control tests all passed.

Regarding @sandyarmstrong's question: I think the two are actually quite similar with arguably a slight lag in the SCAN surveillance. It's worth noting that our surveillance differs from SCAN's program in the type of sample involved. We use the liquid fraction of wastewater, which in our observation tends to lead to a better depiction of current trends, while SCAN uses the solid/sludge fraction, which empirically seems to be more of a multi-day composite measurement. Very much an open question- but in my opinion our use of the liquid fraction seems to confer us with a bit of additional sensitivity to fast temporal dynamics. 

Josh

**Comment by sandyarmstrong** [comment]
Thanks for the detailed answer, fascinating stuff!
