### ISSUE TITLE
Updates have stopped 

### ISSUE THREAD

**Issue by thrawn997** [andersen-lab/SARS-CoV-2_WasteWater_San-Diego#203]
It looks like there haven't been any updates in a couple of weeks despite a big surge in covid. Is this expected?

**Comment by joshuailevy** [comment]
Looking into it- seems like some updates got stuck at the PR approval stage. Should be available via the dash shortly.

**Comment by joshuailevy** [comment]
Should be up to date, thanks for the heads up!
