### ISSUE TITLE
Point Loma Data Erratic Since Nov 2022

### ISSUE THREAD

**Issue by jasonbmiller** [andersen-lab/SARS-CoV-2_WasteWater_San-Diego#35]
Thanks for your tireless work. Is there a reason why the Point Loma data has become almost completely unusable since November? There are wide swings at regular intervals day to day.
![Screenshot](https://user-images.githubusercontent.com/13813610/218331531-43aa3271-f67d-4fa2-b801-af824be51280.jpg)

**Comment by joshuailevy** [comment]
Thanks @jasonbmiller. We'd noticed the increased noise in some of the recent samples, and re-ran those samples on our new PCR machines over the past few weeks. This data is now on the dashboard and shows considerable less variability.

**Comment by jasonbmiller** [comment]
> Thanks @jasonbmiller. We'd noticed the increased noise in some of the recent samples, and re-ran those samples on our new PCR machines over the past few weeks. This data is now on the dashboard and shows considerable less variability.

Wow, thank you so much! I rely on your data to gauge how much risk I take out there in the real world. Your data is the only source we can use these days for that purpose since reported cases data is way below actual. Your work serves those of us out there who are working hard to avoid catching COVID for various personal reasons, not the least of which, pre-existing conditions. 

All the best to you and your team!
