### ISSUE TITLE
Is that a real spike?

### ISSUE THREAD

**Issue by jasonbmiller** [andersen-lab/SARS-CoV-2_WasteWater_San-Diego#94]
Thank you all again for keeping us informed. It is invaluable for those of us who are still trying to avoid COVID. 

Are the last two data points for Point Loma a legitimate spike or an anomaly? That looks like an unrealistic jump. 

Thank you so much!

**Comment by joshuailevy** [comment]
Hi @jasonbmiller! We noticed the same jump and are following that up now to confirm whether or not it is real or if there was some sort of qPCR issue. We'll let you know what we find out as soon as possible.

**Comment by joshuailevy** [comment]
Hi again,
We went back to the qPCR data, and although those samples snuck through our usual quality control filters, there was a large amount variability in the raw data, suggesting possible issues with processing. As a result we have removed those samples from the public data for now.

**Comment by jasonbmiller** [comment]
> Hi again, We went back to the qPCR data, and although those samples snuck through our usual quality control filters, there was a large amount variability in the raw data, suggesting possible issues with processing. As a result we have removed those samples from the public data for now.

Thank you so much! Those of us who are trying to avoid COVID rely on your data heavily. We really appreciate your work.
